# Generated by Django 4.1.8 on 2023-08-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0167_module_status'),
        ('ipam', '0064_clear_search_cache'),
        ('virtualization', '0034_standardize_description_comments'),
        ('netdoc', '0012_discoverable_vm'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routetableentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='arptableentry',
            name='virtual_interface',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='virtualization.vminterface'),
        ),
        migrations.AddField(
            model_name='routetableentry',
            name='nexthop_virtual_if',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='virtualization.vminterface'),
        ),
        migrations.AddField(
            model_name='routetableentry',
            name='vm',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='virtualization.virtualmachine'),
        ),
        migrations.AlterUniqueTogether(
            name='routetableentry',
            unique_together={('device', 'destination', 'distance', 'metric', 'protocol', 'vrf', 'nexthop_if', 'nexthop_virtual_if', 'nexthop_ip', 'vm')},
        ),
    ]
