# Generated by Django 4.1.8 on 2023-08-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0167_module_status'),
        ('virtualization', '0034_standardize_description_comments'),
        ('netdoc', '0013_alter_routetableentry_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='arptableentry',
            unique_together={('interface', 'ip_address', 'mac_address', 'virtual_interface')},
        ),
    ]
