# Generated by Django 4.1.8 on 2023-08-14 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0167_module_status'),
        ('netdoc', '0014_alter_arptableentry_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arptableentry',
            name='interface',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.interface'),
        ),
        migrations.AlterField(
            model_name='routetableentry',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.device'),
        ),
    ]
