# Generated by Django 4.1.8 on 2023-08-14 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0034_standardize_description_comments'),
        ('netdoc', '0015_alter_arptableentry_interface_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arptableentry',
            name='virtual_interface',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='virtualization.vminterface'),
        ),
    ]
